import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Correct import for Google fonts
import "./globals.css"; // Assuming you have global styles
import Header from "../components/header";
import ActiveSectionContextProvider, {
  ActiveSectionContext,
} from "@/context/active-section-context";
export const metadata: Metadata = {
  title: "Prapti | Portfolio",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["latin"], // Add subsets if needed (like 'latin')
  weight: "400", // You can specify weights like "400", "700", etc.
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${inter.className} bg-gray-50 text-gray-950 relative h-[5000px] pt-28 sm:pt-36`}
      >
        <div className="bg-[#fbe2e3] absolute top-[-6rem] -z-10 right-[11rem] h-[31.25rem] w-[31.25rem] rounded-full blur-[10rem] sm:w-[68.75rem]"></div>
        <div className="bg-[#dbd7fb] absolute top-[-1rem] -z-10 left-[-35rem] h-[31.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem]"></div>
        <ActiveSectionContextProvider>
          <Header />
          {children}
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
